Module7 task3
htmlacademy-react/1465455-what-to-watch-5 pull request #16
Opened 2020-11-19 19:46 UTC by begemotv

Этот пуллреквест получился объемным. Посмотрел следующее задание и там уже только тесты. И правильнее, наверное, тестить уже всю бизнес логику.

Есть ряд моментов, в которых я сомневаюсь. Один из них – это списки фильмов. Есть три компонента (FilmList, MoreLikeFilms и MyListFilms), которые очень похожи и чувствую правильно было бы сделать один общий компонент для них, но пока не могу понять, как их объединить. Забирать массивы фильмов нужно из разных мест. Что бы ты посоветовал?

Слегка мне кажется сделал лишнего в компоненте SignInScreen. Сделал для него HOC, который валидирует правильность написания имейла и в случае сабмита неправильного делает красную обводку и выводит сообщение. Увидел это в маркапе, но этого пункта не оказалось в ТЗ. В принципе попрактиковался лишний раз. Нормально так оставить? 

Из того что еще не завершено – события при неудачном сетевом запросе. Пока не знаю, что в них писать.

2020-11-19 20:57 UTC, DmitryMarkov requested changes
Мне кажется ты не очень понял концепцию редакса, локального стейта и хоков. Код выглядит очень сложно и запутанно. Давай сделаем так: всё, что мы берем из API, кладем в стор (редакс), включая статусы isLoading и ошибки. Все вновь созданные хоки со стейтом isLoading удаляем, они будут не нужны. Компоненты-листеры фильмов объединяем, отвязываем от стора и просто передаем списки фильмов на генерацию верстки и конфигурацию через пропсы (делаем их "тупыми")

> Слегка мне кажется сделал лишнего в компоненте SignInScreen. Сделал для него HOC, который валидирует правильность написания имейла и в случае сабмита неправильного делает красную обводку и выводит сообщение. Увидел это в маркапе, но этого пункта не оказалось в ТЗ. В принципе попрактиковался лишний раз. Нормально так оставить?

Нормально. В ТЗ сказано "на усмотрение разработчика".

> Из того что еще не завершено – события при неудачном сетевом запросе. Пока не знаю, что в них писать.

пиши "ошибка сервера". Опять же вывод на усмотрение разработчика. Ты не можешь использовать консолги, но можешь писать в редакс и выводить, например, через тостер https://tomchentw.github.io/react-toastr/ или аналогичный компонент

Кроме того кнопка Post для нового отзыва слишком серая, даже когда не заблочена, а из списка отзывов пропало имя пользователя

2020-11-19 20:57 UTC, DmitryMarkov commented on src/components/film-screen/film-screen.jsx
> +                    : ``
Можно написать и так
```suggestion
                  authorizationStatus === AuthorizationStatus.AUTH
                    && <Link to={`${AppRoute.FILMS}${id}${AppRoute.REVIEW}`} className="btn movie-card__button">Add review</Link>
```

2020-11-19 20:57 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +          ? <Avatar /> : <SignInLink />}
Повторяющиеся части (копипасты) можно вынести в отдельные компоненты

2020-11-19 20:57 UTC, DmitryMarkov commented on src/components/sign-in-screen/sign-in-screen.jsx
> +                <p>Please enter a valid email address</p>
Здечь тоже ренартик лишний и многострочный JSX желательно выделять в круглые скобки
```suggestion
            !isValid && (
              <div className="sign-in__message">
              <p>Please enter a valid email address</p>
```

2020-11-19 20:57 UTC, DmitryMarkov commented on src/const.js
>  export const APIRoute = {
```suggestion
export const ApiRoute = {
```

2020-11-19 20:57 UTC, DmitryMarkov commented on src/hocs/with-error/with-error.jsx
> +      const re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
это лишнее. достаточно валидации средствами html, на самом деле

2020-11-19 20:57 UTC, DmitryMarkov commented on src/hocs/with-review/with-review.jsx
> +const RATING_STARS_COUNT_DEFAULT = `2`;
По умолчанию рейтинг не должен быть выбран, пользователь его выбирает, а у тебя выглядит как будто уже стоит двойка

2020-11-19 20:57 UTC, DmitryMarkov commented on src/hocs/with-review/with-review.jsx
> +  return connect(mapStateToProps, mapDispatchToProps)(WithReview);
засовывать коннекты к редаксув ХОКи, на мой взгляд, довольно спорное решение

2020-11-19 20:57 UTC, DmitryMarkov commented on src/hocs/with-reviews-loaded/with-reviews-loaded.jsx
> +        isFetching: true,
это должно быть в редаксе

2020-11-19 20:57 UTC, DmitryMarkov commented on src/hocs/with-reviews-loaded/with-reviews-loaded.jsx
> +        reviews: null,
это тоже должно быть в редаксе и тогда никакие хоки не нужны

2020-11-19 20:57 UTC, DmitryMarkov commented on src/store/api-actions/api-actions.js
> +    })
нигде нет обработки ошибок серверных запросов (`catch`), в результате есть кецсы когда прелоадер просто вечно крутится

2020-11-21 21:36 UTC, begemotv commented
вроде бы все о чем ты говорил я поправил. очень не уверен в правильности обработки ошибок. практически с этим не работал и не до конца понимаю как правильно. возможно нужно провести консультацию по этой теме

2020-11-22 13:57 UTC, DmitryMarkov requested changes
Логика работы формы добавления комментария все равно нарушена (см. комментарий про звезды и логику работы формы). Со звездами следующий косяк, кроме того, что по умолчанию все пять звезд подсвечены. Если текст уже набран, а звезды не выбраны, то выбор звезды не разблокирует форму с первого раза, а только со второго. 

И еще форма не разблокируется если рейтинг выбран, а текст вставлен из буфера обмена, хотя в нем больше 50 и меньше 400 символов.

Если нужна голосовая консультация, можем созвониться в понедельник или вторник

2020-11-22 13:57 UTC, DmitryMarkov commented on src/components/main-catalog/main-catalog.jsx
> +        movieCardsShownCount <= filteredFilms.length
тогда это можно оформить как переменную hasMoreFilms, создавая ее в mSTP

2020-11-22 13:57 UTC, DmitryMarkov commented on src/components/my-list-button/my-list-button.jsx
> +    dispatch(addToFavorites(id, +status));
конкатенация

2020-11-22 13:57 UTC, DmitryMarkov commented on src/components/my-list-button/my-list-button.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(MyListButton);
зачем два экспорта?

2020-11-22 13:57 UTC, DmitryMarkov commented on src/components/sign-in-screen/sign-in-screen.jsx
> +      isValid: true,
стейт в компонентах в этом проекте не приветствуется. Либо в глобальный стор (редакс), либо в ХОКи.

2020-11-22 13:57 UTC, DmitryMarkov commented on src/hocs/with-review/with-review.jsx
> +const RATING_STARS_COUNT_DEFAULT = `5`;
это не решает проблему, теперь по умолчанию когда форма пустая "горят" пять звезд, ъотя по факту они не выбраны

2020-11-22 13:57 UTC, DmitryMarkov commented on src/store/api-actions/api-actions.js
> +   })
Логика работы формы все равно нарушена.

Читаем ТЗ:

> При нажатии кнопки «Post» и отправки данных форма должна блокироваться. Разблокировка формы происходит в случае успешной отправки или при возникновении ошибки.

при ошибке форма остается заблокированной

> В случае успешной отправки формы пользователь перенаправляется в карточку текущего фильма.

В случае успешной.... а у тебя всегда идет переход (строка 76)

> В случае возникновения ошибки следует уведомить пользователя. Способ отображения ошибки остаётся на усмотрение разработчика.

из-за редиректа на строке 76 пользователь не видит сообщения об ошибке (тоаст), так как он публикуется и сразу идет переход на новую страницу

2020-11-23 17:40 UTC, DmitryMarkov commented on src/components/add-review-screen/add-review-screen.jsx
> +  const idInteger = parseInt(id, 10);
Лучше использовать объект Number

```suggestion
  const idInteger = Number.parseInt(id, 10);
```

2020-11-25 07:38 UTC, DmitryMarkov reviewed
Да, уже почти хорошо 🙂 

Два замечания:

> При нажатии кнопки «Post» и отправки данных форма должна блокироваться. Разблокировка формы происходит в случае успешной отправки или при возникновении ошибки.

У тебя в случае ошибки форма остается заблокированной, а при возникновении ошибки она тоже должна заблокироваться.

И второй момент, что при добавлении коммента, идет переход на страницу фильма и в табе "Комменты" я его не вижу сразу, а должен. Приходится перезагружать страницу

2020-11-25 14:19 UTC, DmitryMarkov approved these changes
Замечания исправлены

2020-11-25 14:19 UTC, merged