Module3 task1
htmlacademy-react/1465455-what-to-watch-5 pull request #7
Opened 2020-10-11 16:20 UTC by begemotv

2020-10-12 17:07 UTC, DmitryMarkov requested changes
В целом, задание выполнено, но есть много замечаний, кроме того шейпы объектов (фильмы и комментарии) лучше вынести в отдельный файл и переиспользовать их внутри компонентов.

2020-10-12 17:07 UTC, DmitryMarkov commented on src/components/film-card/film-card.jsx
> +    previewImg: PropTypes. string.isRequired
Вообще непонятно как с такими ошибками проходит проверка линтера... 🤷 

```suggestion
    previewImg: PropTypes.string.isRequired
```

2020-10-12 17:07 UTC, DmitryMarkov commented on src/components/film-list/film-list.jsx
> +// {`film-${index}`}
комменты кода запрещены

2020-10-12 17:07 UTC, DmitryMarkov commented on src/components/film-list/film-list.jsx
> +  films: PropTypes.array.isRequired,
нужно использовать arrayOf

2020-10-12 17:07 UTC, DmitryMarkov commented on src/components/film-screen/film-screen.jsx
> +      starring
рекомендую все пропсы и деструктуризации сортировать по алфавиту, будет легче и самому и коллегам

2020-10-12 17:07 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +            <Link to="/" className="catalog__genres-link">Thrillers</Link>
зачем?

2020-10-12 17:07 UTC, DmitryMarkov commented on src/index.js
> +// console.log(filteredReviews)
комменты

2020-10-12 17:07 UTC, DmitryMarkov commented on src/index.js
> +const MainFilmData = {
думаю, стоит брать данные из моков

2020-10-14 15:49 UTC, begemotv commented on src/components/add-comment/add-comment.jsx
> +                  <label className="rating__label" htmlFor={`star-${index + 1}`}>Rating {index + 1}</label>
Исправил.

2020-10-14 15:49 UTC, begemotv commented on src/components/add-comment/add-comment.jsx
> +          }}
Исправил

2020-10-14 15:53 UTC, begemotv commented on src/components/add-review-screen/add-review-screen.jsx
> +                <Link to="/films/:id" className="breadcrumbs__link">{name}</Link>
Мог заменить на id из моков, но честно говоря пока не понимаю как настраивать роутинг динамически. Без этого получается одну заглушку на другую заменю.
Оставил здесь как было. Как только буду понимать как настроить - сразу же заменю на реальный id

2020-10-14 15:53 UTC, begemotv commented on src/components/app/app.jsx
> +            film={films[films.length - 1]}
так и есть. пока выполняет роль заглушки

2020-10-14 15:55 UTC, begemotv commented on src/components/film-card/film-card.jsx
> +    previewImg: PropTypes. string.isRequired
🤷
Поправил

2020-10-14 15:56 UTC, begemotv commented on src/components/film-list/film-list.jsx
> +// {`film-${index}`}
Удалил

2020-10-14 15:56 UTC, begemotv commented on src/components/film-list/film-list.jsx
> +  films: PropTypes.array.isRequired,
Исправил

2020-10-14 15:58 UTC, begemotv commented on src/components/film-screen/film-screen.jsx
> +      starring
Отсортировал. А сами моки нормально оставлять не по алфавиту? Когда они по алфавиту сложнее ориентироваться (какой фильм, айди и т.д.)

2020-10-14 15:59 UTC, begemotv commented on src/components/main-screen/main-screen.jsx
> +            <Link to="/" className="catalog__genres-link">Thrillers</Link>
Объективной причины нет
Импортировал Link и почему-то решил все <a> заменить на <Link>. Если это не нужно или вредно - могу заменить на <a>

2020-10-14 16:00 UTC, begemotv commented on src/index.js
> +// console.log(filteredReviews)
Убрал

2020-10-16 08:59 UTC, begemotv commented on src/components/main-screen/main-screen.jsx
> +            <Link to="/" className="catalog__genres-link">Thrillers</Link>
Пересмотрел еще раз вторую лекцию и в ней Игорь говорит, что для всей навигации внутри приложения мы используем <Link />. 
Или фидбек был в том, что я заменил все на Link, но по факту это все равно заглушки с переходом на главную?

2020-10-16 09:53 UTC, begemotv commented on src/components/add-review-screen/add-review-screen.jsx
> +                <Link to="/films/:id" className="breadcrumbs__link">{name}</Link>
Заменил в карточка фильма заглушки на линки с id, но пытаюсь разобраться как забрать этот id и использовать его для рендера нужного компонента.
Его нужно передавать пропом в <Route /> или считывать непосредственно в компоненте из служебного объекта props.match? Первый вариант выглядит оптимальнее, так как не нужно передавать в каждый компонент весь массив фильмов и там уже делать сравнение. Но не могу понять как передать этот проп в роуте

2020-10-16 20:49 UTC, DmitryMarkov commented on src/components/film-screen/film-screen.jsx
> +      starring
в своих проектах я в исключительных случаях отступаю от этого правила. То есть всё сортирую, кроме некоторых случаев, таких как key или id

2020-10-16 20:50 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +            <Link to="/" className="catalog__genres-link">Thrillers</Link>
Там не будет перехода на главную, будет рендер внутри компонента. Можно сделать было генерацию, а так выглядит как копипаста...

2020-10-16 20:53 UTC, DmitryMarkov approved these changes
Замечания исправлены

2020-10-16 20:53 UTC, merged